### ISSUE TITLE
No labels are setup for pull requests

### ISSUE THREAD

**Issue by davemcg3** [team-hack/coding-guidelines#13]
You can pick a color for labels and they make it really easy to look down the list of open pull requests and visually see where they are. Labels you might consider adding:

1. do not merge
2. draft
3. help wanted
4. question

**Comment by vijayxtreme** [comment]
Sounds good! I think we have a help wanted one, but I can do the other labels right now.

**Comment by vijayxtreme** [comment]
Good to go!
